FROM python:3.14-slim

ARG SERVICE_DIR
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PORT=8000

WORKDIR /app
COPY ${SERVICE_DIR}/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt
COPY ${SERVICE_DIR}/ /app/

EXPOSE ${PORT}
CMD python manage.py runserver 0.0.0.0:${PORT}
